language: java
jdk:
  - oraclejdk8
  - openjdk8

env:
  global:
    TERM=dumb

install: true
before_script:
  - nvm install lts/*
  - sudo apt update -y
  - sudo apt install -y python-pip
  - sudo pip install httpie

script:
  - bash gradlew clean build
  - bash gradlew bootRun &
  - sleep 30
  - http :8080/

cache:
  directories:
    - $HOME/.gradle/
    - .gradle/
