language: java
jdk:
  - oraclejdk8
  - openjdk8

install: true
before_script: nvm install tls/*

script:
  - npm i
  - bash gradlew clean build

cache:
  directories:
    - $HOME/.gradle/
    - node_modules/
    - .gradle/
